name: Practice-1
on: push
jobs:
    job-1:
        runs-on: ubuntu-latest
        steps:
        - name: checkout the repo
          uses: actions/checkout@v4

        - name: multi-line-execution
          run: script.sh