name: Practice-1
on: push
jobs:
    job-1:
        runs-on: ubuntu-latest
        outputs:
            job-1-file-output: ${{steps.upload-file.outputs.artifact}}
            job-1-folder-output: ${{steps.upload-folder.outputs.artifact-id}}
        steps:
        - name: checkout the repo
          uses: actions/checkout@v4

        - name: checkout the contents of the repo
          run: |
            pwd
            ls -lrta
            tree
        - name: execute the shell script
          run: |
            chmod +x *.sh
            ./script.sh > output.txt 2>&1
            mkdir test
            touch test/samplefile{1..10}
        - name: upload the file as an artifact
          id: upload-file
          uses: actions/upload-artifact@v4
          with:
            name: upload-artifact
            path: output.txt
        - name: upload the folder as an artifact
          id: upload-folder
          uses: actions/upload-artifact@v4
          with:
            name: folder-artifact
            path: test/
    job-2:
        needs: job-1
        runs-on: ubuntu-latest
        env:
          FILE_NAME: ${{ needs.job-1.outputs.job-1-file-output}}
          FOLDER_NAME: ${{ needs.job-1.outputs.job-1-folder-output}}
        steps:
        - name: download the artifact file
          uses: actions/download-artifact@v4
          with:
            name: upload-artifact
            path: .
        - name: download the artifacts folder
          uses: actions/download-artifact@v4
          with:
            name: folder-artifact
            path: .
        - name: check the contents of the directory post download
          run: |
            tree
            echo "file name is $FILE_NAME"
            echo "folder name is $FOLDER_NAME"
