name: Hello world
on: push
jobs:
    hello-world:
        runs-on: ubuntu-latest
        steps:
        - name: echo
          run: echo "this is a test"
        - name: checkout the current repo
          uses: actions/checkout@v4
        - name: checkout another repo
          uses: actions/checkout@v4
          with:
            repository: rahulchandrak/github-actions-solar-system
            path: github-actions-solar-system
        - name: check the contents of the checked out repos
          run: ls -lrt